<?php
			$optionsArray = array( 'totals' => array( 'id' => array( 'totalsType' => '' ),
'fileNo' => array( 'totalsType' => '' ),
'fileName' => array( 'totalsType' => '' ),
'fileType' => array( 'totalsType' => '' ),
'fileDuration' => array( 'totalsType' => '' ),
'fileSubject' => array( 'totalsType' => '' ),
'fileTitle' => array( 'totalsType' => '' ),
'fileClassLevel' => array( 'totalsType' => '' ),
'fileTeacherName' => array( 'totalsType' => '' ),
'fileRaw' => array( 'totalsType' => '' ),
'fileMD5' => array( 'totalsType' => '' ),
'fileStatus' => array( 'totalsType' => '' ),
'filePath' => array( 'totalsType' => '' ),
'censorApproveTime' => array( 'totalsType' => '' ),
'censorUsername' => array( 'totalsType' => '' ),
'censoReson' => array( 'totalsType' => '' ),
'censorStatus' => array( 'totalsType' => '' ),
'entryUserName' => array( 'totalsType' => '' ),
'entryTime' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'fileNo',
'fileName',
'fileType',
'fileSubject',
'fileTitle',
'fileClassLevel',
'fileTeacherName',
'censorApproveTime',
'censorUsername',
'censoReson',
'censorStatus',
'entryUserName',
'entryTime',
'fileRaw',
'fileDuration',
'fileMD5',
'fileStatus',
'filePath' ),
'exportFields' => array( 'fileNo',
'fileName',
'fileType',
'fileRaw',
'fileSubject',
'fileTitle',
'fileDuration',
'fileClassLevel',
'fileTeacherName',
'censorApproveTime',
'censorUsername',
'censoReson',
'censorStatus',
'entryUserName',
'entryTime',
'fileMD5',
'fileStatus',
'filePath' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'fileNo' => array( 'export_field1' ),
'fileName' => array( 'export_field2' ),
'fileType' => array( 'export_field3' ),
'fileSubject' => array( 'export_field4' ),
'fileTitle' => array( 'export_field5' ),
'fileClassLevel' => array( 'export_field6' ),
'fileTeacherName' => array( 'export_field7' ),
'censorApproveTime' => array( 'export_field9' ),
'censorUsername' => array( 'export_field10' ),
'censoReson' => array( 'export_field11' ),
'censorStatus' => array( 'export_field12' ),
'entryUserName' => array( 'export_field15' ),
'entryTime' => array( 'export_field16' ),
'fileRaw' => array( 'export_field' ),
'fileDuration' => array( 'export_field8' ),
'fileMD5' => array( 'export_field13' ),
'fileStatus' => array( 'export_field14' ),
'filePath' => array( 'export_field17' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field',
'export_field4',
'export_field5',
'export_field8',
'export_field6',
'export_field7',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field15',
'export_field16',
'export_field13',
'export_field14',
'export_field17' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field8' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field17' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field15',
'export_field16',
'export_field',
'export_field8',
'export_field13',
'export_field14',
'export_field17' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field',
'export_field4',
'export_field5',
'export_field8',
'export_field6',
'export_field7',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field15',
'export_field16',
'export_field13',
'export_field14',
'export_field17' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field1' => array( 'field' => 'fileNo',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'fileName',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'fileType',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'fileSubject',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'fileTitle',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'fileClassLevel',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'fileTeacherName',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'censorApproveTime',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'censorUsername',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'censoReson',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'censorStatus',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'entryUserName',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'entryTime',
'type' => 'export_field' ),
'export_field' => array( 'field' => 'fileRaw',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'fileDuration',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'fileMD5',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'fileStatus',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'filePath',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 7,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>