<?php
			$optionsArray = array( 'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'fileNo',
'fileName',
'fileType',
'fileSubject',
'fileTitle',
'fileClassLevel',
'fileTeacherName',
'fileRaw',
'entryUserName',
'entryTime',
'fileDuration',
'fileMD5',
'fileTeacherInfo',
'filedate',
'fileStatus',
'filePath',
'producerName' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array(  ),
'fieldItems' => array( 'fileNo' => array( 'integrated_edit_field' ),
'fileName' => array( 'integrated_edit_field1' ),
'fileType' => array( 'integrated_edit_field2' ),
'fileSubject' => array( 'integrated_edit_field3' ),
'fileTitle' => array( 'integrated_edit_field4' ),
'fileClassLevel' => array( 'integrated_edit_field5' ),
'fileTeacherName' => array( 'integrated_edit_field6' ),
'fileRaw' => array( 'integrated_edit_field7' ),
'entryUserName' => array( 'integrated_edit_field14' ),
'entryTime' => array( 'integrated_edit_field15' ),
'fileDuration' => array( 'integrated_edit_field12' ),
'fileMD5' => array( 'integrated_edit_field13' ),
'fileTeacherInfo' => array( 'integrated_edit_field8' ),
'filedate' => array( 'integrated_edit_field9' ),
'fileStatus' => array( 'integrated_edit_field10' ),
'filePath' => array( 'integrated_edit_field11' ),
'producerName' => array( 'integrated_edit_field16' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => true,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'edit_header' ),
'above-grid' => array( 'edit_message' ),
'below-grid' => array( 'edit_save',
'edit_back_list',
'edit_close',
'hamburger' ),
'grid' => array( 'master_info',
'integrated_edit_field',
'integrated_edit_field9',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field4',
'integrated_edit_field3',
'integrated_edit_field6',
'integrated_edit_field8',
'integrated_edit_field16',
'integrated_edit_field5',
'integrated_edit_field7',
'integrated_edit_field10',
'integrated_edit_field13',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field14',
'integrated_edit_field15' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'edit_header' => 'top',
'edit_message' => 'above-grid',
'edit_save' => 'below-grid',
'edit_back_list' => 'below-grid',
'edit_close' => 'below-grid',
'hamburger' => 'below-grid',
'master_info' => 'grid',
'integrated_edit_field' => 'grid',
'integrated_edit_field9' => 'grid',
'integrated_edit_field1' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field4' => 'grid',
'integrated_edit_field3' => 'grid',
'integrated_edit_field6' => 'grid',
'integrated_edit_field8' => 'grid',
'integrated_edit_field16' => 'grid',
'integrated_edit_field5' => 'grid',
'integrated_edit_field7' => 'grid',
'integrated_edit_field10' => 'grid',
'integrated_edit_field13' => 'grid',
'integrated_edit_field11' => 'grid',
'integrated_edit_field12' => 'grid',
'integrated_edit_field14' => 'grid',
'integrated_edit_field15' => 'grid' ),
'itemLocations' => array( 'master_info' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field9' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field8' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field16' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field10' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field13' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field11' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field12' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field14' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field15' => array( 'location' => 'grid',
'cellId' => 'c3' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'edit_header' => array( 'edit_header' ),
'hamburger' => array( 'hamburger' ),
'edit_reset' => array( 'edit_reset' ),
'edit_message' => array( 'edit_message' ),
'edit_save' => array( 'edit_save' ),
'edit_back_list' => array( 'edit_back_list' ),
'edit_close' => array( 'edit_close' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field16' ),
'master_info' => array( 'master_info' ),
'edit_view' => array( 'edit_view' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'master_info',
'integrated_edit_field',
'integrated_edit_field9',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field4',
'integrated_edit_field3',
'integrated_edit_field6',
'integrated_edit_field8',
'integrated_edit_field16',
'integrated_edit_field5',
'integrated_edit_field7',
'integrated_edit_field10',
'integrated_edit_field13',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field14',
'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'edit' => array( 'updateSelected' => false ) );
			$pageArray = array( 'id' => 'edit',
'type' => 'edit',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_save',
'edit_back_list',
'edit_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'master_info',
'integrated_edit_field',
'integrated_edit_field9',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field4',
'integrated_edit_field3',
'integrated_edit_field6',
'integrated_edit_field8',
'integrated_edit_field16',
'integrated_edit_field5',
'integrated_edit_field7',
'integrated_edit_field10',
'integrated_edit_field13',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field14',
'integrated_edit_field15' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => true,
'separateLabels' => false ) ),
'items' => array( 'edit_header' => array( 'type' => 'edit_header',
'title' => array( 'page' => 'edit',
'table' => 'IngestInfo',
'type' => 7 ) ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'edit_reset',
'edit_view' ) ),
'edit_reset' => array( 'type' => 'edit_reset' ),
'edit_message' => array( 'type' => 'edit_message' ),
'edit_save' => array( 'type' => 'edit_save' ),
'edit_back_list' => array( 'type' => 'edit_back_list' ),
'edit_close' => array( 'type' => 'edit_close' ),
'integrated_edit_field' => array( 'field' => 'fileNo',
'type' => 'integrated_edit_field',
'updateOnEdit' => false,
'orientation' => 1 ),
'integrated_edit_field1' => array( 'field' => 'fileName',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field2' => array( 'field' => 'fileType',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field3' => array( 'field' => 'fileSubject',
'type' => 'integrated_edit_field',
'updateOnEdit' => false,
'orientation' => 1 ),
'integrated_edit_field4' => array( 'field' => 'fileTitle',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'integrated_edit_field5' => array( 'field' => 'fileClassLevel',
'type' => 'integrated_edit_field',
'updateOnEdit' => false,
'orientation' => 1 ),
'integrated_edit_field6' => array( 'field' => 'fileTeacherName',
'type' => 'integrated_edit_field',
'updateOnEdit' => false,
'orientation' => 1 ),
'integrated_edit_field7' => array( 'field' => 'fileRaw',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field14' => array( 'field' => 'entryUserName',
'type' => 'integrated_edit_field',
'updateOnEdit' => false,
'orientation' => 1 ),
'integrated_edit_field15' => array( 'field' => 'entryTime',
'type' => 'integrated_edit_field',
'updateOnEdit' => false,
'orientation' => 1 ),
'integrated_edit_field12' => array( 'field' => 'fileDuration',
'type' => 'integrated_edit_field',
'updateOnEdit' => false,
'orientation' => 1 ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'playlistSub' => 'true' ) ),
'integrated_edit_field13' => array( 'field' => 'fileMD5',
'type' => 'integrated_edit_field',
'updateOnEdit' => false,
'orientation' => 1 ),
'integrated_edit_field8' => array( 'field' => 'fileTeacherInfo',
'type' => 'integrated_edit_field',
'orientation' => 1 ),
'edit_view' => array( 'type' => 'edit_view' ),
'integrated_edit_field9' => array( 'field' => 'filedate',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field10' => array( 'field' => 'fileStatus',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field11' => array( 'field' => 'filePath',
'type' => 'integrated_edit_field',
'orientation' => 1,
'updateOnEdit' => false ),
'integrated_edit_field16' => array( 'field' => 'producerName',
'type' => 'integrated_edit_field',
'orientation' => 1 ) ),
'dbProps' => array(  ),
'version' => 7,
'pageWidth' => 'full' );
		?>