<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_playlistmain  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

		  
	if ($values['playlistOnairDate'] <> $oldvalues['playlistOnairDate']) {

			$SQLCommand = "SELECT * FROM playlistSub WHERE (playlistID=".$values['id'].") ";
	
				$RS = CustomQuery($SQLCommand);
				while ($data = db_fetch_array($RS)) {

					FileMoveFolder($data['mediaInfoID'],"",$data["id"]);

				}
			
	}


// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
